[
  {"id": 1, "name": "Lionel Messi", "aliases": ["Messi", "Leo Messi"], "position": "RW / AM", "foot": "Left"},
  {"id": 2, "name": "Cristiano Ronaldo", "aliases": ["Ronaldo", "CR7"], "position": "ST", "foot": "Right"},
  {"id": 3, "name": "Kylian Mbappe", "aliases": ["Mbappe"], "position": "ST / LW", "foot": "Right"},
  {"id": 4, "name": "Erling Haaland", "aliases": ["Haaland"], "position": "ST", "foot": "Left"},
  {"id": 5, "name": "Kevin De Bruyne", "aliases": ["De Bruyne", "KDB"], "position": "CM / AM", "foot": "Right"},
  {"id": 6, "name": "Vinicius Junior", "aliases": ["Vinicius", "Vini Jr"], "position": "LW", "foot": "Right"},
  {"id": 7, "name": "Jude Bellingham", "aliases": ["Bellingham"], "position": "AM / CM", "foot": "Right"},
  {"id": 8, "name": "Harry Kane", "aliases": ["Kane"], "position": "ST", "foot": "Right"},
  {"id": 9, "name": "Mohamed Salah", "aliases": ["Salah"], "position": "RW", "foot": "Left"},
  {"id": 10, "name": "Rodri", "aliases": ["Rodrigo Hernandez"], "position": "DM", "foot": "Right"},
  {"id": 11, "name": "Bukayo Saka", "aliases": ["Saka"], "position": "RW", "foot": "Left"},
  {"id": 12, "name": "Phil Foden", "aliases": ["Foden"], "position": "LW / AM", "foot": "Left"},
  {"id": 13, "name": "Antoine Griezmann", "aliases": ["Griezmann"], "position": "ST / AM", "foot": "Left"},
  {"id": 14, "name": "Lautaro Martinez", "aliases": ["Lautaro"], "position": "ST", "foot": "Right"},
  {"id": 15, "name": "Declan Rice", "aliases": ["Rice"], "position": "DM / CM", "foot": "Right"},
  {"id": 16, "name": "Martin Odegaard", "aliases": ["Odegaard"], "position": "AM", "foot": "Left"},
  {"id": 17, "name": "Virgil van Dijk", "aliases": ["Van Dijk"], "position": "CB", "foot": "Right"},
  {"id": 18, "name": "William Saliba", "aliases": ["Saliba"], "position": "CB", "foot": "Right"},
  {"id": 19, "name": "Ruben Dias", "aliases": ["Dias"], "position": "CB", "foot": "Right"},
  {"id": 20, "name": "Thibaut Courtois", "aliases": ["Courtois"], "position": "GK", "foot": "Left"},
  {"id": 21, "name": "Alisson Becker", "aliases": ["Alisson"], "position": "GK", "foot": "Right"},
  {"id": 22, "name": "Marc-Andre ter Stegen", "aliases": ["Ter Stegen"], "position": "GK", "foot": "Right"},
  {"id": 23, "name": "Ederson", "aliases": [], "position": "GK", "foot": "Left"},
  {"id": 24, "name": "Antonio Rudiger", "aliases": ["Rudiger"], "position": "CB", "foot": "Right"},
  {"id": 25, "name": "John Stones", "aliases": ["Stones"], "position": "CB / DM", "foot": "Right"},
  {"id": 26, "name": "Kyle Walker", "aliases": ["Walker"], "position": "RB", "foot": "Right"},
  {"id": 27, "name": "Achraf Hakimi", "aliases": ["Hakimi"], "position": "RB", "foot": "Right"},
  {"id": 28, "name": "Theo Hernandez", "aliases": ["Theo"], "position": "LB", "foot": "Left"},
  {"id": 29, "name": "Federico Valverde", "aliases": ["Valverde"], "position": "CM / RM", "foot": "Right"},
  {"id": 30, "name": "Toni Kroos", "aliases": ["Kroos"], "position": "CM", "foot": "Right"},
  {"id": 31, "name": "Luka Modric", "aliases": ["Modric"], "position": "CM", "foot": "Right"},
  {"id": 32, "name": "Bernardo Silva", "aliases": ["Bernardo"], "position": "RW / AM", "foot": "Left"},
  {"id": 33, "name": "Bruno Fernandes", "aliases": ["Bruno"], "position": "AM", "foot": "Right"},
  {"id": 34, "name": "Son Heung-min", "aliases": ["Son"], "position": "LW / ST", "foot": "Both"},
  {"id": 35, "name": "Jamal Musiala", "aliases": ["Musiala"], "position": "AM / LW", "foot": "Right"},
  {"id": 36, "name": "Florian Wirtz", "aliases": ["Wirtz"], "position": "AM", "foot": "Right"},
  {"id": 37, "name": "Leroy Sane", "aliases": ["Sane"], "position": "RW / LW", "foot": "Left"},
  {"id": 38, "name": "Kingsley Coman", "aliases": ["Coman"], "position": "LW / RW", "foot": "Right"},
  {"id": 39, "name": "Serge Gnabry", "aliases": ["Gnabry"], "position": "RW / LW", "foot": "Right"},
  {"id": 40, "name": "Joshua Kimmich", "aliases": ["Kimmich"], "position": "DM / RB", "foot": "Right"},
  {"id": 41, "name": "Leon Goretzka", "aliases": ["Goretzka"], "position": "CM", "foot": "Right"},
  {"id": 42, "name": "Alphonso Davies", "aliases": ["Davies"], "position": "LB", "foot": "Left"},
  {"id": 43, "name": "Kim Min-jae", "aliases": ["Kim"], "position": "CB", "foot": "Right"},
  {"id": 44, "name": "Matthijs de Ligt", "aliases": ["De Ligt"], "position": "CB", "foot": "Right"},
  {"id": 45, "name": "Dayot Upamecano", "aliases": ["Upamecano"], "position": "CB", "foot": "Right"},
  {"id": 46, "name": "Manuel Neuer", "aliases": ["Neuer"], "position": "GK", "foot": "Right"},
  {"id": 47, "name": "Victor Osimhen", "aliases": ["Osimhen"], "position": "ST", "foot": "Right"},
  {"id": 48, "name": "Khvicha Kvaratskhelia", "aliases": ["Kvaratskhelia", "Kvara"], "position": "LW", "foot": "Right"},
  {"id": 49, "name": "Rafael Leao", "aliases": ["Leao"], "position": "LW", "foot": "Right"},
  {"id": 50, "name": "Theo Hernandez", "aliases": [], "position": "LB", "foot": "Left"},
  {"id": 51, "name": "Mike Maignan", "aliases": ["Maignan"], "position": "GK", "foot": "Right"},
  {"id": 52, "name": "Christian Pulisic", "aliases": ["Pulisic"], "position": "RW / LW", "foot": "Right"},
  {"id": 53, "name": "Ruben Loftus-Cheek", "aliases": ["Loftus-Cheek"], "position": "CM", "foot": "Right"},
  {"id": 54, "name": "Olivier Giroud", "aliases": ["Giroud"], "position": "ST", "foot": "Left"},
  {"id": 55, "name": "Ciro Immobile", "aliases": ["Immobile"], "position": "ST", "foot": "Right"},
  {"id": 56, "name": "Paulo Dybala", "aliases": ["Dybala"], "position": "AM / RW", "foot": "Left"},
  {"id": 57, "name": "Romelu Lukaku", "aliases": ["Lukaku"], "position": "ST", "foot": "Left"},
  {"id": 58, "name": "Tammy Abraham", "aliases": ["Abraham"], "position": "ST", "foot": "Right"},
  {"id": 59, "name": "Lorenzo Pellegrini", "aliases": ["Pellegrini"], "position": "AM", "foot": "Right"},
  {"id": 60, "name": "Gianluca Mancini", "aliases": ["Mancini"], "position": "CB", "foot": "Right"},
  {"id": 61, "name": "Rui Patricio", "aliases": ["Patricio"], "position": "GK", "foot": "Left"},
  {"id": 62, "name": "Federico Chiesa", "aliases": ["Chiesa"], "position": "LW / RW", "foot": "Right"},
  {"id": 63, "name": "Dusan Vlahovic", "aliases": ["Vlahovic"], "position": "ST", "foot": "Left"},
  {"id": 64, "name": "Adrien Rabiot", "aliases": ["Rabiot"], "position": "CM", "foot": "Left"},
  {"id": 65, "name": "Bremer", "aliases": [], "position": "CB", "foot": "Right"},
  {"id": 66, "name": "Wojciech Szczesny", "aliases": ["Szczesny"], "position": "GK", "foot": "Right"},
  {"id": 67, "name": "Hakan Calhanoglu", "aliases": ["Calhanoglu"], "position": "DM", "foot": "Right"},
  {"id": 68, "name": "Nicolo Barella", "aliases": ["Barella"], "position": "CM", "foot": "Right"},
  {"id": 69, "name": "Henrikh Mkhitaryan", "aliases": ["Mkhitaryan"], "position": "CM / AM", "foot": "Right"},
  {"id": 70, "name": "Federico Dimarco", "aliases": ["Dimarco"], "position": "LB", "foot": "Left"},
  {"id": 71, "name": "Alessandro Bastoni", "aliases": ["Bastoni"], "position": "CB", "foot": "Left"},
  {"id": 72, "name": "Benjamin Pavard", "aliases": ["Pavard"], "position": "CB / RB", "foot": "Right"},
  {"id": 73, "name": "Marcus Thuram", "aliases": ["Thuram"], "position": "ST", "foot": "Right"},
  {"id": 74, "name": "Yann Sommer", "aliases": ["Sommer"], "position": "GK", "foot": "Right"},
  {"id": 75, "name": "Pedri", "aliases": [], "position": "CM", "foot": "Right"},
  {"id": 76, "name": "Gavi", "aliases": [], "position": "CM", "foot": "Right"},
  {"id": 77, "name": "Frenkie de Jong", "aliases": ["De Jong"], "position": "CM / DM", "foot": "Right"},
  {"id": 78, "name": "Ilkay Gundogan", "aliases": ["Gundogan"], "position": "CM / AM", "foot": "Right"},
  {"id": 79, "name": "Robert Lewandowski", "aliases": ["Lewandowski"], "position": "ST", "foot": "Right"},
  {"id": 80, "name": "Raphinha", "aliases": [], "position": "RW", "foot": "Left"},
  {"id": 81, "name": "Ferran Torres", "aliases": ["Ferran"], "position": "RW / ST", "foot": "Right"},
  {"id": 82, "name": "Joao Felix", "aliases": ["Felix"], "position": "LW / AM", "foot": "Right"},
  {"id": 83, "name": "Ronald Araujo", "aliases": ["Araujo"], "position": "CB / RB", "foot": "Right"},
  {"id": 84, "name": "Andreas Christensen", "aliases": ["Christensen"], "position": "CB", "foot": "Right"},
  {"id": 85, "name": "Jules Kounde", "aliases": ["Kounde"], "position": "RB / CB", "foot": "Right"},
  {"id": 86, "name": "Alejandro Balde", "aliases": ["Balde"], "position": "LB", "foot": "Left"},
  {"id": 87, "name": "Dani Carvajal", "aliases": ["Carvajal"], "position": "RB", "foot": "Right"},
  {"id": 88, "name": "Ferland Mendy", "aliases": ["Mendy"], "position": "LB", "foot": "Left"},
  {"id": 89, "name": "Eder Militao", "aliases": ["Militao"], "position": "CB", "foot": "Right"},
  {"id": 90, "name": "Rodrygo", "aliases": [], "position": "RW / LW", "foot": "Right"},
  {"id": 91, "name": "Joselu", "aliases": [], "position": "ST", "foot": "Right"},
  {"id": 92, "name": "Eduardo Camavinga", "aliases": ["Camavinga"], "position": "CM / LB", "foot": "Left"},
  {"id": 93, "name": "Aurelien Tchouameni", "aliases": ["Tchouameni"], "position": "DM / CB", "foot": "Right"},
  {"id": 94, "name": "Arda Guler", "aliases": ["Guler"], "position": "AM / RW", "foot": "Left"},
  {"id": 95, "name": "Brahim Diaz", "aliases": ["Brahim"], "position": "AM / RW", "foot": "Right"},
  {"id": 96, "name": "Alejandro Garnacho", "aliases": ["Garnacho"], "position": "LW / RW", "foot": "Right"},
  {"id": 97, "name": "Kobbie Mainoo", "aliases": ["Mainoo"], "position": "CM / DM", "foot": "Right"},
  {"id": 98, "name": "Rasmus Hojlund", "aliases": ["Hojlund"], "position": "ST", "foot": "Left"},
  {"id": 99, "name": "Marcus Rashford", "aliases": ["Rashford"], "position": "LW / ST", "foot": "Right"},
  {"id": 100, "name": "Andre Onana", "aliases": ["Onana"], "position": "GK", "foot": "Right"}
]
